### PR TITLE
Created navbar, login and signup

### PR DESCRIPTION
**Pull request by ShounakA**
Just the views no E2E tests yet. WIP
#7 #3

### CODE REVIEW

**Comment by ShounakA** [comment]
last commit bddd6ea: I added unit tests for my views and added them to frontend maven plugin to be run on travis ci.

**Comment by jobinmatt** [comment]
is the routing of the sign-up supposed to be functional with this PR? It wasn't working when I tested.

**Comment by ShounakA** [comment]
It should be working. The units tests are passing

**Comment by ShounakA** [comment]
the button and link for login in navbar dont work

**Pull request merged**
